#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /login
  methods: ['POST']

logout:
  path: /logout
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path:       /refresh
  controller: gesdinet.jwtrefreshtoken::refresh